### ISSUE TITLE
FOR RUSLAN: EP PDF gives error `undefined method 'truncate' for nil:NilClass

### ISSUE THREAD

**Issue by RuslanHamidullin** [bitzesty/qae#354]
```
8:06:58 web.1  | Started GET "/users/form_answers/6.pdf" for 127.0.0.1 at 2015-04-15 18:06:58 +0100
18:06:58 web.1  | Processing by Users::FormAnswersController#show as PDF
18:06:58 web.1  |   Parameters: {"id"=>"6"}
18:06:58 web.1  |   User Load (1.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
18:06:58 web.1  |   Account Load (0.9ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT 1  [["id", 1]]
18:06:58 web.1  |   FormAnswer Load (1.1ms)  SELECT  "form_answers".* FROM "form_answers" WHERE "form_answers"."account_id" = $1 AND "form_answers"."id" = $2 LIMIT 1  [["account_id", 1], ["id", 6]]
18:06:58 web.1  |   User Load (1.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
18:06:59 web.1  |   Supporter Load (1.3ms)  SELECT "supporters".* FROM "supporters" WHERE "supporters"."form_answer_id" = $1  [["form_answer_id", 6]]
18:06:59 web.1  |   SupportLetter Load (1.5ms)  SELECT "support_letters".* FROM "support_letters" WHERE "support_letters"."form_answer_id" = $1 AND "support_letters"."manual" = 't'  [["form_answer_id", 6]]
18:06:59 web.1  |   SupportLetterAttachment Load (1.3ms)  SELECT  "support_letter_attachments".* FROM "support_letter_attachments" WHERE "support_letter_attachments"."support_letter_id" = $1 LIMIT 1  [["support_letter_id", 1]]
18:06:59 web.1  | Completed 500 Internal Server Error in 697ms
18:06:59 web.1  |
18:06:59 web.1  | NoMethodError - undefined method `truncate' for nil:NilClass:
18:06:59 web.1  |   app/pdf_generators/qae_pdf_forms/custom_questions/supporter_lists.rb:51:in `render_support_letter'
18:06:59 web.1  |   app/pdf_generators/qae_pdf_forms/custom_questions/supporter_lists.rb:41:in `render_supporter'
18:06:59 web.1  |   app/pdf_generators/qae_pdf_forms/custom_questions/supporter_lists.rb:27:in `block in render_supporters_list'
18:06:59 web.1  |   activerecord (4.2.0) lib/active_record/relation/delegation.rb:46:in `each'
18:06:59 web.1  |   app/pdf_generators/qae_pdf_forms/custom_questions/supporter_lists.rb:17:in `render_supporters_list'
18:06:59 web.1  |   app/pdf_generators/qae_pdf_forms/custom_questions/supporter_lists.rb:10:in `render_supporters'
18:06:59 web.1  |   app/pdf_generators/qae_pdf_forms/general/question_pointer.rb:294:in `block in question_answer'
18:06:59 web.1  |   prawn (1.3.0) lib/prawn/document/bounding_box.rb:287:in `indent'
18:06:59 web.1  |   prawn (1.3.0) lib/prawn/document.rb:483:in `indent'
18:06:59 web.1  |   app/pdf_generators/qae_pdf_forms/general/question_pointer.rb:293:in `question_answer'
18:06:59 web.1  |   app/pdf_generators/qae_pdf_forms/general/question_pointer.rb:143:in `block in render_context_and_answer_blocks'
18:06:59 web.1  |   prawn (1.3.0) lib/prawn/document/bounding_box.rb:287:in `indent'
18:06:59 web.1  |   prawn (1.3.0) lib/prawn/document.rb:483:in `indent'
18:06:59 web.1  |   app/pdf_generators/qae_pdf_forms/general/question_pointer.rb:137:in `render_context_and_answer_blocks'
18:06:59 web.1  |   app/pdf_generators/qae_pdf_forms/general/question_pointer.rb:121:in `question_block'
18:06:59 web.1  |   app/pdf_generators/qae_pdf_forms/general/question_pointer.rb:79:in `render!'
18:06:59 web.1  |   app/pdf_generators/qae_pdf_forms/general/step_pointer.rb:29:in `block in render!'
18:06:59 web.1  |   app/pdf_generators/qae_pdf_forms/general/step_pointer.rb:26:in `render!'
18:06:59 web.1  |   app/pdf_generators/form_pdf.rb:48:in `block in generate!'
18:06:59 web.1  |   app/pdf_generators/form_pdf.rb:45:in `generate!'
18:06:59 web.1  |   app/pdf_generators/form_pdf.rb:39:in `initialize'
18:06:59 web.1  |   app/decorators/form_answer_decorator.rb:13:in `pdf_generator'
18:06:59 web.1  |   app/controllers/users/form_answers_controller.rb:11:in `block (2 levels) in show'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_controller/metal/mime_responds.rb:216:in `respond_to'
18:06:59 web.1  |   app/controllers/users/form_answers_controller.rb:9:in `show'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
18:06:59 web.1  |   actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
18:06:59 web.1  |   actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
18:06:59 web.1  |   actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
18:06:59 web.1  |   activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
18:06:59 web.1  |   actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
18:06:59 web.1  |   actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
18:06:59 web.1  |   rack-mini-profiler (0.9.2) lib/mini_profiler/profiling_methods.rb:108:in `block in profile_method'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
18:06:59 web.1  |   warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
18:06:59 web.1  |   warden (1.2.3) lib/warden/manager.rb:34:in `call'
18:06:59 web.1  |   rack (1.6.0) lib/rack/etag.rb:24:in `call'
18:06:59 web.1  |   rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
18:06:59 web.1  |   rack (1.6.0) lib/rack/head.rb:13:in `call'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
18:06:59 web.1  |   rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
18:06:59 web.1  |   rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
18:06:59 web.1  |   activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
18:06:59 web.1  |   activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
18:06:59 web.1  |   activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
18:06:59 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
18:06:59 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb
```

**Comment by matthewford** [comment]
@RuslanHamidullin this still an issue?

**Comment by RuslanHamidullin** [comment]
Nope it fixed. cLosing
