### ISSUE TITLE
FOR DEVS: manual upload of Support Letter causes error (probably on attempt to check file with Virus Scanner)

### ISSUE THREAD

**Issue by RuslanHamidullin** [bitzesty/qae#387]
```
14:16:06 web.1  | Started POST "/users/form_answers/3/support_letter_attachments" for 127.0.0.1 at 2015-04-18 14:16:06 +0100
14:16:06 web.1  | Processing by Users::SupportLetterAttachmentsController#create as */*
14:16:06 web.1  |   Parameters: {"form"=>{"supporter_letters_list"=>{"0"=>{"letter_of_support"=>#<ActionDispatch::Http::UploadedFile:0x007f844fcc7218 @tempfile=#<Tempfile:/var/folders/sf/q_8kpn7154vg0648p3yxt4zr0000gp/T/RackMultipart20150418-10113-1dmgsp1.png>, @original_filename="test.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"form[supporter_letters_list][0][letter_of_support]\"; filename=\"test.png\"\r\nContent-Type: image/png\r\n">}}}, "form_answer_id"=>"3"}
14:16:06 web.1  |   User Load (5.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
14:16:06 web.1  |   Account Load (4.2ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT 1  [["id", 1]]
14:16:06 web.1  |   FormAnswer Load (7.8ms)  SELECT  "form_answers".* FROM "form_answers" WHERE "form_answers"."account_id" = $1 AND "form_answers"."id" = $2 LIMIT 1  [["account_id", 1], ["id", 3]]
14:16:06 web.1  |    (3.2ms)  BEGIN
14:16:06 web.1  |   User Load (6.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
14:16:06 web.1  |   SQL (7.9ms)  INSERT INTO "support_letter_attachments" ("attachment", "user_id", "original_filename", "form_answer_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["attachment", "test.png"], ["user_id", 1], ["original_filename", "test.png"], ["form_answer_id", 3], ["created_at", "2015-04-18 13:16:06.399028"], ["updated_at", "2015-04-18 13:16:06.399028"]]
14:16:06 web.1  |    (4.2ms)  ROLLBACK
14:16:06 web.1  | Completed 500 Internal Server Error in 118ms
14:16:06 web.1  |
14:16:06 web.1  | NoMethodError - undefined method `strip' for nil:NilClass:
14:16:06 web.1  |   /Users/frankiebiscuit/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/http/header.rb:17:in `block in initialize_http_header'
14:16:06 web.1  |   /Users/frankiebiscuit/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/http/header.rb:15:in `initialize_http_header'
14:16:06 web.1  |   /Users/frankiebiscuit/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/http/generic_request.rb:44:in `initialize'
14:16:06 web.1  |   faraday (0.9.1) lib/faraday/adapter/net_http.rb:62:in `create_request'
14:16:06 web.1  |   faraday (0.9.1) lib/faraday/adapter/net_http.rb:82:in `perform_request'
14:16:06 web.1  |   faraday (0.9.1) lib/faraday/adapter/net_http.rb:40:in `block in call'
14:16:06 web.1  |   faraday (0.9.1) lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
14:16:06 web.1  |   faraday (0.9.1) lib/faraday/adapter/net_http.rb:32:in `call'
14:16:06 web.1  |   faraday_middleware (0.9.1) lib/faraday_middleware/response_middleware.rb:30:in `call’
```

**Comment by RuslanHamidullin** [comment]
I suppose it causes here https://github.com/bitzesty/qae/blob/master/app/models/support_letter_attachment.rb#L30
