### ISSUE TITLE
EP Form | AJAX removing of Support Letter (strange behavior)

### ISSUE THREAD

**Issue by RuslanHamidullin** [bitzesty/qae#535]
The you removing existing Support Letter it causes strange errors in Browser and App logs
Here the screens:
![support_letter_removing_strange_behavior](https://cloud.githubusercontent.com/assets/358508/7723831/7d944628-fef4-11e4-837e-a986e859bfc6.png)

From my point of view - issue in controller level.
System do DELETE request properly, but then tries to do normal redirect to dashboard (even if it's JS request)
Log says about it:
```
Started DELETE "/users/form_answers/24/support_letters/8" for 127.0.0.1 at 2015-05-20 13:32:20 +0300
Processing by Users::SupportLettersController#destroy as */*
  Parameters: {"form_answer_id"=>"24", "id"=>"8"}
  User Load (2.0ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
  Account Load (0.4ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT 1  [["id", 1]]
  FormAnswer Load (0.6ms)  SELECT  "form_answers".* FROM "form_answers" WHERE "form_answers"."account_id" = $1 AND "form_answers"."id" = $2 LIMIT 1  [["account_id", 1], ["id", 24]]
  SupportLetter Load (0.4ms)  SELECT  "support_letters".* FROM "support_letters" WHERE "support_letters"."form_answer_id" = $1 AND "support_letters"."id" = $2 LIMIT 1  [["form_answer_id", 24], ["id", 8]]
   (0.3ms)  BEGIN
  SupportLetterAttachment Load (0.8ms)  SELECT  "support_letter_attachments".* FROM "support_letter_attachments" WHERE "support_letter_attachments"."support_letter_id" = $1 LIMIT 1  [["support_letter_id", 8]]
  SQL (0.2ms)  DELETE FROM "support_letter_attachments" WHERE "support_letter_attachments"."id" = $1  [["id", 8]]
  SQL (0.6ms)  DELETE FROM "support_letters" WHERE "support_letters"."id" = $1  [["id", 8]]
   (15.0ms)  COMMIT
Redirected to http://localhost:3000/dashboard
Completed 302 Found in 49ms (ActiveRecord: 20.4ms)

Started DELETE "/dashboard" for 127.0.0.1 at 2015-05-20 13:32:21 +0300
** [Raven] User excluded error: #<ActionController::RoutingError: No route matches [DELETE] "/dashboard">

ActionController::RoutingError (No route matches [DELETE] "/dashboard"):
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
```

BTW: AJAX removing of Supporter works fine.

**Comment by RuslanHamidullin** [comment]
Fixed by https://github.com/bitzesty/qae/pull/539
