### ISSUE TITLE
Organisational Chart Upload validation error

### ISSUE THREAD

**Issue by RuslanHamidullin** [bitzesty/qae#537]
```
Started POST "/form/26/attachments.json" for 127.0.0.1 at 2015-05-20 16:18:02 +0300
Processing by FormController#add_attachment as JSON
  Parameters: {"authenticity_token"=>"abwZG0QWYPpBlnZdN8eSCA275tVWo/HfdusHn0CDKZBY9sOhBlZ17b9N2R+3oB6K679L6AsZuK6xAo07EmjpVw==", "question_key"=>"org_chart", "form"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x007fca94eab350 @tempfile=#<Tempfile:/tmp/RackMultipart20150520-9066-1pn6l75.jpg>, @original_filename="friday.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"form[file]\"; filename=\"friday.jpg\"\r\nContent-Type: image/jpeg\r\n">}, "id"=>"26"}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
  Account Load (0.2ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT 1  [["id", 1]]
  FormAnswer Load (0.3ms)  SELECT  "form_answers".* FROM "form_answers" WHERE "form_answers"."account_id" = $1 AND "form_answers"."id" = $2 LIMIT 1  [["account_id", 1], ["id", 26]]
  FormAnswerAttachment Load (0.2ms)  SELECT "form_answer_attachments".* FROM "form_answer_attachments" WHERE "form_answer_attachments"."form_answer_id" = $1  [["form_answer_id", 26]]
   (0.3ms)  BEGIN
   (0.2ms)  SELECT COUNT(*) FROM "form_answer_attachments" WHERE "form_answer_attachments"."question_key" = $1  [["question_key", "org_chart"]]
   (0.2ms)  ROLLBACK
Completed 422 Unprocessable Entity in 39ms

ActiveRecord::RecordInvalid - Validation failed: Maximum amount of these kind of files reached.:
  activerecord (4.2.0) lib/active_record/validations.rb:79:in `raise_record_invalid'
  activerecord (4.2.0) lib/active_record/validations.rb:43:in `save!'
  activerecord (4.2.0) lib/active_record/attribute_methods/dirty.rb:29:in `save!'
  activerecord (4.2.0) lib/active_record/transactions.rb:291:in `block in save!'
```

Validation is need to be corrected, because if there is at least of one FormAnswerAttachment with "org_chart" question key in db -> then always would be raised validation issue.

```
  def question_key_correctness
    # possible improvements:
    # - validating all upload questions in this way
    # - smart collecting max-attachments information from the form structure
    if question_key == "org_chart" && new_record?
      if self.class.where(question_key: self.question_key).count > 0
        errors.add(:base, "Maximum amount of these kind of files reached.")
      end
    end
  end
```

Probably need to add form_answer_id condition  above ^

**Comment by RuslanHamidullin** [comment]
This one is fixed
