### ISSUE TITLE
Audit Certificate Generation: are broken for trade and development forms

### ISSUE THREAD

**Issue by RuslanHamidullin** [bitzesty/qae#562]
```
ActiveHash::RecordNotFound (Couldn't find QuestionLabels::AuditCertificateLabel with ID=sustainable development):
  app/pdf_generators/pdf_audit_certificates/general/shared_elements.rb:59:in `table_headers'
  app/pdf_generators/pdf_audit_certificates/general/shared_elements.rb:38:in `render_financial_table'
  app/pdf_generators/audit_certificate_pdf.rb:41:in `render_first_page'
  app/pdf_generators/audit_certificate_pdf.rb:33:in `render_content'
  app/pdf_generators/audit_certificate_pdf.rb:29:in `generate!'
  app/pdf_generators/audit_certificate_pdf.rb:25:in `initialize'
  app/decorators/form_answer_decorator.rb:28:in `new'
  app/decorators/form_answer_decorator.rb:28:in `pdf_audit_certificate_generator'
```

**Comment by RuslanHamidullin** [comment]
Fixed  by https://github.com/bitzesty/qae/commit/144f25dee7a6473b8018b9d2eb2ed60664db7dfd
